import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule, MatCheckboxModule, MatSelectModule, MatIconModule, MatListModule, MatSidenavModule, MatRadioModule, MatSliderModule, MatStepperModule, MatTableModule, MatSortModule, MatTooltipModule, MatToolbarModule, MatTabsModule, MatSnackBar, MatSnackBarModule, MatSlideToggleModule, MatRippleModule, MatProgressSpinner, MatProgressSpinnerModule, MatPaginatorModule, MatProgressBarModule, MatNativeDateModule, MatMenuModule, MatInputModule, MatGridListModule, MatExpansionModule, MatChipsModule, MatAutocompleteModule, MatButtonToggleModule, MatCardModule, MatDatepickerModule, MatDialogModule } from "@angular/material";
import { CdkTableModule } from '@angular/cdk/table';
@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatCheckboxModule,
    MatIconModule,
    MatListModule,
    CdkTableModule,
    MatSelectModule,
    MatSidenavModule,
    MatRadioModule,
    MatSliderModule,
    MatStepperModule,
    MatTableModule,
    MatSortModule,
    MatTableModule,
    MatTooltipModule,
    MatToolbarModule,
    MatTabsModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatRippleModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatMenuModule,
    MatInputModule,
    MatGridListModule,
    MatExpansionModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatCardModule,
    MatDatepickerModule,
    MatDialogModule
],
  declarations: [],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatIconModule,
    MatListModule,
    CdkTableModule,
    MatSelectModule,
    MatSidenavModule,
    MatRadioModule,
    MatSliderModule,
    MatStepperModule,
    MatTableModule,
    MatSortModule,
    MatTableModule,
    MatTooltipModule,
    MatToolbarModule,
    MatTabsModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatRippleModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatMenuModule,
    MatInputModule,
    MatGridListModule,
    MatExpansionModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatCardModule,
    MatDatepickerModule,
    MatDialogModule
  ]
})
export class MaterialModule { }
